//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Becarios
    {
        public int Id_Becario { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int Edad { get; set; }
        public double Promedio { get; set; }
        public bool AdeudaMaterias { get; set; }
        public double IngresoMensual { get; set; }
        public bool EsBecadoProspera { get; set; }
        public bool Discapacidad { get; set; }
        public int Id_Municipio { get; set; }
        public Nullable<bool> EsBecado { get; set; }
        public Nullable<System.DateTime> FechaEvaluacionbeca { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
